name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run EF Core Migrations for PropriedadeService
        run: dotnet-ef database update --project ./ProproedadeService/PropriedadeService.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.PROPRIEDADE_CONNECTION_STRING }}
          PATH: ${{ env.PATH }}:/github/home/.dotnet/tools

      - name: Run EF Core Migrations for AlertaService
        run: dotnet-ef database update --project ./AlertaService/AlertaService.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.ALERTA_CONNECTION_STRING }}
          PATH: ${{ env.PATH }}:/github/home/.dotnet/tools

      - name: Run EF Core Migrations for AuthService
        run: dotnet-ef database update --project ./AuthService/AuthService.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AUTH_CONNECTION_STRING }}
          PATH: ${{ env.PATH }}:/github/home/.dotnet/tools

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push AuthService image
        uses: docker/build-push-action@v5
        with:
          context: ./AuthService
          push: true
          tags: ${{ env.REGISTRY }}/authservice:${{ env.IMAGE_TAG }}

      - name: Build and push PropriedadeService image
        uses: docker/build-push-action@v5
        with:
          context: ./ProproedadeService
          push: true
          tags: ${{ env.REGISTRY }}/propriedadeservice:${{ env.IMAGE_TAG }}

      - name: Build and push SersorService image
        uses: docker/build-push-action@v5
        with:
          context: ./SersorService
          push: true
          tags: ${{ env.REGISTRY }}/sersorservice:${{ env.IMAGE_TAG }}

      - name: Build and push AlertaService image
        uses: docker/build-push-action@v5
        with:
          context: ./AlertaService
          push: true
          tags: ${{ env.REGISTRY }}/alertaservice:${{ env.IMAGE_TAG }}
